import { afterAll, afterEach, beforeAll, beforeEach, describe, it } from '@ohos/hypium';
import FileUtils from '../../../../main/ets/common/utils/FIleUtils';

export default function FileUtilsTest() {
  describe('FileUtils', () => {
    beforeAll(() => {
    });

    beforeEach(() => {
    });

    afterEach(() => {
    });

    afterAll(() => {
    });

    it('getInstance returns singleton instance', 0, () => {

    });

  });
}
